services:
  psql:
    build:
      context: ./
      dockerfile: ./docker/psql/Dockerfile
    container_name: weatherforecast_psql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_DB=weatherforecast
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    container_name: weatherforecast_api
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST_ADDRESS=host.docker.internal
      - POSTGRES_HOST_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_DB=weatherforecast
      - SSL_MODE=disable
      - SERVER_PORT=8000
      - OPENWEATHERAPI_ID=q1w2e3r4t5y6
    depends_on:
      psql:
        condition: service_healthy
    command: bash -c "go mod download && go build -o app && ./app"
